### ISSUE TITLE
while user typing , code will not valid at compiler check and nimsuggest check

### ISSUE THREAD

**Issue by bung87** [bung87/nimlsp#2]

**Comment by iacore** [comment]
This is an example error. Any hints on how to fix this?

```
[Error] Request textDocument/documentSymbol failed.
Error: The received response has neither a result nor an error property.
	at handleInvalidMessage (/home/user/.vscode-oss/extensions/bung87.vscode-nim-lsp-0.0.17/node_modules/vscode-jsonrpc/lib/main.js:530:40)
	at processMessageQueue (/home/user/.vscode-oss/extensions/bung87.vscode-nim-lsp-0.0.17/node_modules/vscode-jsonrpc/lib/main.js:279:17)
	at Immediate.<anonymous> (/home/user/.vscode-oss/extensions/bung87.vscode-nim-lsp-0.0.17/node_modules/vscode-jsonrpc/lib/main.js:260:13)
	at processImmediate (node:internal/timers:464:21)
```

**Comment by bung87** [comment]
need check nimlsp log , the extension side does not have much info useful, nimsuggest is not perfect now , problem may coming from there.

**Comment by iacore** [comment]
It is from a node package named like vscode-lsp-client or something.

nimlsp sometimes respond to message with invalid response (without result nor error)

I looked at the code before, but can't find an obvious bug
